'use client';
import { useCallback, useEffect, useState } from 'react';
export type CloudDevice = { id: string; name: string; online: boolean; revoked: boolean; lastSeen: number };
export async function cloudCall<T>(action: string, params: Record<string, unknown> = {}): Promise<T> {
 const r = await fetch('/api/remote', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({action,...params}), cache:'no-store' });
 const b = await r.json(); if (!r.ok) throw new Error(b.error || '서버 연결 실패'); return b.result;
}
export default function CloudConnection({ cloud }: { cloud: boolean }) {
 const [serverAddress,setServerAddress]=useState('https://think-along.ai.kr');
 const [account,setAccount]=useState<{email:string}|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[devices,setDevices]=useState<CloudDevice[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[signup,setSignup]=useState(false),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{ const me=await cloudCall<{account:{email:string}}>('me');setAccount(me.account);setDevices(await cloudCall<CloudDevice[]>('devices')); },[]);
 useEffect(()=>{if(cloud){setServerAddress(location.origin);void refresh().catch(()=>{});}},[cloud,refresh]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="tw-cloud-connect" aria-label="작업 공간 연결"><div className="tw-filter-row"><strong>{cloud?'서버 저장 · 원격 작업':'로컬 전용 작업 공간'}</strong><a className="tw-text-button" href={cloud?'http://127.0.0.1:3002/projects?source=local':'https://think-along.ai.kr/projects?source=cloud'}>{cloud?'로컬 웹에서 열기':'Think Along 서버에서 열기'} ↗</a></div>{cloud&&<details open={!account}><summary>{account?`${account.email} · 기기 연결 관리`:'서버 작업 공간 로그인'}</summary>{!account?<form className="tw-cloud-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await cloudCall(signup?'signup':'login',{email,password});setPassword('');await refresh();setNotice('로그인했습니다. 등록된 프로젝트 찾기를 눌러주세요.');});}}><p>로컬 데이터 저장은 선택입니다. 연결한 프로젝트의 대화·결정·작업 기록이 서버에 보존됩니다.</p><label>이메일<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<input type="password" autoComplete={signup?'new-password':'current-password'} minLength={12} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)} required/></label><div className="tw-actions"><button type="submit" className="tw-primary" disabled={busy}>{signup?'계정 만들기':'로그인'}</button><button type="button" className="tw-secondary" onClick={()=>setSignup(!signup)}>{signup?'로그인으로':'새 계정 만들기'}</button></div><small>원격 작업용 계정으로 로그인하세요.</small></form>:<div className="tw-cloud-form"><p>연결할 컴퓨터의 프로젝트 폴더에서 아래 명령을 실행한 뒤 코드를 입력하세요.</p><code>{`talo remote pair --server ${serverAddress} --sync-records --allow-run --share-diff`}</code><small>대화·결정·작업 기록과 요청한 diff가 서버에 저장됩니다. 파일 전체와 AI 인증 키는 동기화하지 않습니다.</small><form onSubmit={e=>{e.preventDefault();void act(async()=>{const r=await cloudCall<{name:string}>('pair.approve',{code});setNotice(`${r.name} 연결을 승인했습니다. CLI에서 talo remote start를 실행하세요.`);setCode('');await refresh();});}}><label>기기 연결 코드<input value={code} onChange={e=>setCode(e.target.value)} autoComplete="off" required/></label><button className="tw-primary" disabled={busy}>이 기기 연결 승인</button></form><button className="tw-secondary" onClick={()=>void act(refresh)} disabled={busy}>기기 상태 새로고침</button>{devices.map(d=><div className="tw-connection-row" key={d.id}><span>{d.name} · {d.revoked?'연결 해제됨':d.online?'온라인':'오프라인'}</span>{!d.revoked&&<button className="tw-secondary" disabled={busy} onClick={()=>void act(async()=>{await cloudCall('revoke',{deviceId:d.id});await refresh();setNotice('새 원격 요청을 차단했습니다. 이미 실행 중인 작업은 기기에서 확인하세요.');})}>연결 해제</button>}</div>)}<button className="tw-secondary" onClick={()=>void act(async()=>{await cloudCall('logout');setAccount(null);setDevices([]);location.assign('/projects?source=cloud');})}>로그아웃</button></div>}</details>}{error&&<p role="alert" className="tw-alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
