import { mkdirSync, existsSync, readFileSync, writeFileSync, renameSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
const [major, minor] = process.versions.node.split('.').map(Number);
if (major < 22 || (major === 22 && minor < 18)) throw new Error('Node.js 22.18 이상이 필요합니다.');
const bin = join(homedir(), '.local/bin');
const target = join(bin, 'think-along');
const entry = fileURLToPath(new URL('./think-along.mjs', import.meta.url));
const marker = '# Think Along managed CLI launcher';
const quote = value => "'" + value.replaceAll("'", "'\\''") + "'";
mkdirSync(bin, { recursive: true });
if (existsSync(target) && !readFileSync(target, 'utf8').includes(marker)) throw new Error('기존 think-along 실행 파일이 있어 덮어쓰지 않았습니다: ' + target);
const script = '#!/bin/sh\n' + marker + '\nexec ' + quote(process.execPath) + ' --disable-warning=MODULE_TYPELESS_PACKAGE_JSON ' + quote(entry) + ' "$@"\n';
const temp = target + '.tmp-' + process.pid;
writeFileSync(temp, script, { mode: 0o755 });
renameSync(temp, target);
console.log('설치 완료: ' + target);
console.log('프로젝트 폴더에서 think-along 실행. ~/.local/bin이 PATH에 있어야 합니다.');
